const STORAGE_KEY="ap-qr-scanner.records.v2";let records=[],scanner=null,scannerRunning=false,pendingRecord=null;const $=id=>document.getElementById(id);
document.addEventListener("DOMContentLoaded",()=>{loadRecords();renderRecords();$("startScanBtn").addEventListener("click",startScanner);$("cancelScanBtn").addEventListener("click",cancelScanner);$("saveNextBtn").addEventListener("click",savePendingAndScanNext);$("cancelResultBtn").addEventListener("click",cancelPending);$("exportBtn").addEventListener("click",exportCsv);$("clearAllBtn").addEventListener("click",()=>$('clearDialog').showModal());$("cancelClearBtn").addEventListener("click",()=>$('clearDialog').close());$("confirmClearBtn").addEventListener("click",clearAll);$("closeMessageBtn").addEventListener("click",()=>$('messageDialog').close());$("cancelEditBtn").addEventListener("click",()=>$('editDialog').close());$("editForm").addEventListener("submit",saveEdit);if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{})});
function loadRecords(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");records=Array.isArray(s)?s:[]}catch{records=[]}}function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(records))}
function renderRecords(){const list=$("recordsList"),count=records.length;$("recordCount").textContent=count;$("recordSummary").textContent=`${count} ${count===1?"record":"records"}`;$("exportBtn").disabled=count===0;$("clearAllBtn").disabled=count===0;if(!count){list.innerHTML='<div class="empty-state">No APs scanned yet.</div>';return}list.innerHTML=records.map((r,i)=>`<article class="record"><div class="record-main"><div class="record-row"><span class="record-label">#</span><span class="record-value">${i+1}</span></div><div class="record-row"><span class="record-label">Serial Number</span><span class="record-value">${escapeHtml(r.serial)}</span></div><div class="record-row"><span class="record-label">MAC Address</span><span class="record-value mono">${escapeHtml(r.mac)}</span></div></div><div class="record-actions"><button class="secondary" data-action="edit" data-id="${escapeAttr(r.id)}">Edit</button><button class="danger-outline" data-action="delete" data-id="${escapeAttr(r.id)}">Delete</button></div></article>`).join("");list.querySelectorAll("button[data-action='edit']").forEach(b=>b.addEventListener("click",()=>openEdit(b.dataset.id)));list.querySelectorAll("button[data-action='delete']").forEach(b=>b.addEventListener("click",()=>deleteRecord(b.dataset.id)))}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function escapeAttr(v){return escapeHtml(v)}
function normaliseMac(value) {
  const hex = String(value ?? "").replace(/[^0-9A-Fa-f]/g, "").toUpperCase();
  if (hex.length !== 12) return String(value ?? "").trim().toLowerCase();
  return hex.match(/.{2}/g).join(":").toLowerCase();
}

function parseQrText(text){const fields={};for(const part of String(text).split(";")){const colon=part.indexOf(":");if(colon<0)continue;const key=part.slice(0,colon).trim().toUpperCase(),value=part.slice(colon+1).trim();if(key)fields[key]=value}const serial=(fields["PROG#"]||"").trim(),mac=normaliseMac(fields["MAC"] || "").replace(/\s+/g,"");if(!serial||!mac)throw new Error("Unable to read this AP.\n\nThe QR code must contain:\nPROG#\nMAC");return{serial,mac}}
function duplicateMessage(c,ignoreId=null){const s=c.serial.toLowerCase(),m=normaliseMac(c.mac),f=records.find(r=>r.id!==ignoreId&&(r.serial.toLowerCase()===s||normaliseMac(r.mac)===m));if(!f)return"";if(f.serial.toLowerCase()===s)return`This Serial Number has already been scanned: ${f.serial}`;return`This MAC Address has already been scanned: ${f.mac}`}
async function startScanner(){if(scannerRunning)return;showScreen("scannerScreen");setStatus("scannerStatus","Starting camera…");if(!window.Html5Qrcode){setStatus("scannerStatus","The QR scanner library could not be loaded. Open the site once while online, then try again.",true);return}if(!window.isSecureContext&&location.hostname!=="localhost"){setStatus("scannerStatus","Camera access normally requires HTTPS. Open the web app using an HTTPS address.",true);return}scanner=new Html5Qrcode("reader",{verbose:false});const configs=[{facingMode:{exact:"environment"}},{facingMode:"environment"}];let lastError=null;for(const config of configs){try{await scanner.start(config,{fps:10,qrbox:{width:280,height:280},aspectRatio:1},onScanSuccess,()=>{});scannerRunning=true;setStatus("scannerStatus","Camera ready. Position the QR code inside the box.",false,true);return}catch(e){lastError=e}}scanner=null;setStatus("scannerStatus",cameraErrorMessage(lastError),true)}
async function onScanSuccess(decodedText){if(!scannerRunning)return;try{await stopScanner();const parsed=parseQrText(decodedText),dup=duplicateMessage(parsed);if(dup){showMessage("Duplicate AP",`${dup}\n\nThe AP was not added to the inventory.`);showScreen("homeScreen");return}pendingRecord=parsed;$("pendingSerial").textContent=parsed.serial;$("pendingMac").textContent=parsed.mac;$("resultStatus").textContent="";showScreen("resultScreen")}catch(e){await stopScanner();showMessage("QR code error",e.message||"The QR code could not be read.");showScreen("homeScreen")}}
async function stopScanner(){if(!scanner)return;try{if(scannerRunning)await scanner.stop();await scanner.clear()}catch{}scannerRunning=false;scanner=null;$("reader").innerHTML=""}async function cancelScanner(){await stopScanner();showScreen("homeScreen")}
async function savePendingAndScanNext(){if(!pendingRecord)return;const dup=duplicateMessage(pendingRecord);if(dup){setStatus("resultStatus",dup,true);return}records.push({id:crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,serial:pendingRecord.serial,mac:pendingRecord.mac,savedAt:new Date().toISOString()});persist();renderRecords();pendingRecord=null;await startScanner()}function cancelPending(){pendingRecord=null;showScreen("homeScreen")}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}function setStatus(id,text,error=false,success=false){const e=$(id);e.textContent=text||"";e.classList.toggle("error",error);e.classList.toggle("success",success)}function showMessage(title,text){$("messageTitle").textContent=title;$("messageText").textContent=text;$("messageDialog").showModal()}
function openEdit(id){const r=records.find(x=>x.id===id);if(!r)return;$("editId").value=id;$("editSerial").value=r.serial;$("editMac").value=normaliseMac(r.mac);$("editError").textContent="";$("editDialog").showModal()}
function saveEdit(e){e.preventDefault();const id=$("editId").value,serial=$("editSerial").value.trim(),mac=normaliseMac($("editMac").value).replace(/\s+/g,""),err=$("editError");if(!serial||!mac){err.textContent="Both Serial Number and MAC Address are required.";return}const dup=duplicateMessage({serial,mac},id);if(dup){err.textContent=dup;return}const r=records.find(x=>x.id===id);if(!r)return;r.serial=serial;r.mac=mac;persist();renderRecords();$("editDialog").close()}
function deleteRecord(id){const r=records.find(x=>x.id===id);if(!r)return;if(!confirm(`Delete ${r.serial}?`))return;records=records.filter(x=>x.id!==id);persist();renderRecords()}function clearAll(){records=[];persist();renderRecords();$("clearDialog").close()}
function exportCsv(){if(!records.length)return;const rows=[["Serial Number","MAC Address"],...records.map(r=>[r.serial,r.mac])],csv="\uFEFF"+rows.map(row=>row.map(csvEscape).join(",")).join("\r\n")+"\r\n",blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a"),date=new Date().toISOString().slice(0,10);a.href=url;a.download=`AP_Inventory_${date}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}function csvEscape(v){const s=String(v??"");return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function cameraErrorMessage(e){const n=e?.name||"";if(n==="NotAllowedError"||n==="PermissionDeniedError")return"Camera access was denied. Allow camera access for this website in your browser settings, then try again.";if(n==="NotFoundError"||n==="DevicesNotFoundError")return"No camera was found. Check that this device has a camera and that it is available to the browser.";if(n==="NotReadableError"||n==="TrackStartError")return"The camera is already in use or could not be started. Close other camera apps/tabs and try again.";return`The camera could not be started. ${e?.message||"Check browser camera permissions and try again."}`}
